/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5db85c14bcbe47264d82335d
*
* You will get 10% discount for each one of your friends
* 
*/
import { Component } from '@angular/core';
import { OnInit } from '@angular/core';
// Import Services
import { HorseService } from '../../services/horse.service';
// Import Models
import { Horse } from '../../domain/cavaleo_db/horse';

// START - USED SERVICES

// END - USED SERVICES

/**
 * This component shows a list of Horse
 * @class HorseListComponent
 */
@Component({
    selector: 'app-horse-list',
    templateUrl: './horse-list.component.html',
    styleUrls: ['./horse-list.component.css']
})
export class HorseListComponent implements OnInit {
    list: Horse[];
    search: any = {};
    idSelected: string;
    constructor(
        private horseService: HorseService,
    ) { }

    /**
     * Init
     */
    ngOnInit(): void {
        this.horseService.list().subscribe(list => this.list = list);
    }

    /**
     * Select Horse to remove
     *
     * @param {string} id Id of the Horse to remove
     */
    selectId(id: string) {
        this.idSelected = id;
    }

    /**
     * Remove selected Horse
     */
    deleteItem() {
        this.horseService.remove(this.idSelected).subscribe(data => this.list = this.list.filter(el => el._id !== this.idSelected));
    }

}
