<?php /** 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5db85c14bcbe47264d82335d
*
* You will get 10% discount for each one of your friends
* 
*/
?>
<?php
	require_once './db/dbCavaleo_dbManager.php';
	
/*
 * SCHEMA DB Horse
 * 
	{
		birthdate: {
			type: 'Date', 
			required : true
		},
		name: {
			type: 'String', 
			required : true
		},
		//RELAZIONI
		
		
		//RELAZIONI ESTERNE
		
		owner: {
			type: Schema.ObjectId,
			ref : "Horse"
		},
		
	}
 * 
 */


//CRUD METHODS


//CRUD - CREATE


$app->post('/horse',	function () use ($app){

	$body = json_decode($app->request()->getBody());
	
	$params = array (
		'birthdate'	=> $body->birthdate,
		'name'	=> $body->name,
		
		'owner' => isset($body->owner)?$body->owner:'',
	);

	$obj = makeQuery("INSERT INTO horse (_id, birthdate, name , owner )  VALUES ( null, :birthdate, :name , :owner   )", $params, false);
    
	
	echo json_encode($body);
	
});
	
//CRUD - REMOVE

$app->delete('/horse/:id',	function ($id) use ($app){
	
	$params = array (
		'id'	=> $id,
	);

	makeQuery("DELETE FROM horse WHERE _id = :id LIMIT 1", $params);

});

//CRUD - FIND BY owner

$app->get('/horse/findByowner/:key',	function ($key) use ($app){	

	$params = array (
		'key'	=> $key,
	);
	makeQuery("SELECT * FROM horse WHERE owner = :key", $params);
	
});
	
//CRUD - GET ONE
	
$app->get('/horse/:id',	function ($id) use ($app){
	$params = array (
		'id'	=> $id,
	);
	
	$obj = makeQuery("SELECT * FROM horse WHERE _id = :id LIMIT 1", $params, false);
	
	
	
	echo json_encode($obj);
	
});
	
	
//CRUD - GET LIST

$app->get('/horse',	function () use ($app){
	makeQuery("SELECT * FROM horse");
});


//CRUD - EDIT

$app->post('/horse/:id',	function ($id) use ($app){

	$body = json_decode($app->request()->getBody());
	
	$params = array (
		'id'	=> $id,
		'birthdate'	    => $body->birthdate,
		'name'	    => $body->name,
		'owner'      => isset($body->owner)?$body->owner:'' 
	);

	$obj = makeQuery("UPDATE horse SET  birthdate = :birthdate,  name = :name  , owner=:owner  WHERE _id = :id LIMIT 1", $params, false);
    
	
	echo json_encode($body);
    	
});


/*
 * CUSTOM SERVICES
 *
 *	These services will be overwritten and implemented in  Custom.js
 */

			
?>